### ISSUE TITLE
Comments Required

### ISSUE THREAD

**Issue by kunal-halder577** [kunal-halder577/Tic-Tac-Toe#3]
### Comments Required
**comments in MainFrame.java is required.**

**Comment by EvanPaules** [comment]
I can help

**Comment by kunal-halder577** [comment]
Sure! That will be great

**Comment by EvanPaules** [comment]
could you assign the issue to me please

**Comment by kunal-halder577** [comment]
You're now assigned to this issue.

**Comment by shivam0277** [comment]
please assign me this issue i would like to work on this .

**Comment by kunal-halder577** [comment]
Okk.
